Watching for file changes with StatReloader
C:\Users\anton\PycharmProjects\django\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\anton\PycharmProjects\django\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /prefix/about/ HTTP/1.1" 200 27
"GET /prefix/ HTTP/1.1" 200 13
"GET /prefix HTTP/1.1" 301 0
"GET /prefix/ HTTP/1.1" 200 13
C:\Users\anton\PycharmProjects\django\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
Index page accessed
"GET /prefix/ HTTP/1.1" 200 13
"GET /prefix/about HTTP/1.1" 301 0
Error in about page: division by zero
Traceback (most recent call last):
  File "C:\Users\anton\PycharmProjects\django\myproject\myapp\views.py", line 16, in about
    result = 1 / 0
             ~~^~~
ZeroDivisionError: division by zero
"GET /prefix/about/ HTTP/1.1" 200 27
C:\Users\anton\PycharmProjects\django\myproject\myproject\settings.py changed, reloading.
INFO 2023-08-27 21:31:42,367 autoreload 9100 10772 Watching for file changes with StatReloader
INFO 2023-08-27 21:31:55,664 views 9100 3164 Index page accessed
INFO 2023-08-27 21:31:55,665 basehttp 9100 3164 "GET /prefix/ HTTP/1.1" 200 13
ERROR 2023-08-27 21:32:02,832 views 9100 3164 Error in about page: division by zero
Traceback (most recent call last):
  File "C:\Users\anton\PycharmProjects\django\myproject\myapp\views.py", line 16, in about
    result = 1 / 0
             ~~^~~
ZeroDivisionError: division by zero
INFO 2023-08-27 21:32:02,833 basehttp 9100 3164 "GET /prefix/about/ HTTP/1.1" 200 27
INFO 2023-08-28 19:35:36,650 autoreload 11288 3000 Watching for file changes with StatReloader
WARNING 2023-08-28 19:35:41,539 log 11288 7336 Not Found: /
WARNING 2023-08-28 19:35:41,539 basehttp 11288 7336 "GET / HTTP/1.1" 404 2169
WARNING 2023-08-28 19:35:41,576 log 11288 7336 Not Found: /favicon.ico
WARNING 2023-08-28 19:35:41,576 basehttp 11288 7336 "GET /favicon.ico HTTP/1.1" 404 2220
INFO 2023-08-28 19:35:55,920 views 11288 7336 Index page accessed
INFO 2023-08-28 19:35:55,921 basehttp 11288 7336 "GET /prefix/ HTTP/1.1" 200 13
INFO 2023-08-28 19:45:35,657 autoreload 11288 3000 C:\Users\anton\PycharmProjects\django\myproject\myproject\urls.py changed, reloading.
INFO 2023-08-28 19:45:36,147 autoreload 2252 3876 Watching for file changes with StatReloader
WARNING 2023-08-28 19:45:51,317 log 2252 7876 Not Found: /prefix/
WARNING 2023-08-28 19:45:51,317 basehttp 2252 7876 "GET /prefix/ HTTP/1.1" 404 2429
WARNING 2023-08-28 19:45:55,538 log 2252 7876 Not Found: /prefix/
WARNING 2023-08-28 19:45:55,539 basehttp 2252 7876 "GET /prefix/ HTTP/1.1" 404 2429
INFO 2023-08-28 19:45:57,753 views 2252 7876 Index page accessed
INFO 2023-08-28 19:45:57,754 basehttp 2252 7876 "GET / HTTP/1.1" 200 13
INFO 2023-08-29 19:14:21,184 autoreload 11008 4576 Watching for file changes with StatReloader
INFO 2023-08-29 19:15:01,101 views 11008 10708 Index page accessed
INFO 2023-08-29 19:15:01,102 basehttp 11008 10708 "GET / HTTP/1.1" 200 13
WARNING 2023-08-29 19:15:01,136 log 11008 10708 Not Found: /favicon.ico
WARNING 2023-08-29 19:15:01,136 basehttp 11008 10708 "GET /favicon.ico HTTP/1.1" 404 2441
INFO 2023-08-29 19:22:00,221 autoreload 11592 10748 Watching for file changes with StatReloader
INFO 2023-08-30 09:13:39,111 autoreload 13356 9000 Watching for file changes with StatReloader
INFO 2023-08-30 09:14:42,654 autoreload 11980 12936 Watching for file changes with StatReloader
INFO 2023-08-30 09:14:49,797 views 11980 4652 Index page accessed
INFO 2023-08-30 09:14:49,798 basehttp 11980 4652 "GET / HTTP/1.1" 200 13
WARNING 2023-08-30 09:14:50,752 log 11980 8020 Not Found: /favicon.ico
WARNING 2023-08-30 09:14:50,752 basehttp 11980 8020 "GET /favicon.ico HTTP/1.1" 404 2442
INFO 2023-08-30 09:15:02,405 basehttp 11980 13728 "GET /about HTTP/1.1" 301 0
ERROR 2023-08-30 09:15:02,533 views 11980 2648 Error in about page: division by zero
Traceback (most recent call last):
  File "C:\PY\django\myproject\myapp\views.py", line 16, in about
    result = 1 / 0
             ~~^~~
ZeroDivisionError: division by zero
INFO 2023-08-30 09:15:02,536 basehttp 11980 2648 "GET /about/ HTTP/1.1" 200 27
INFO 2023-08-30 09:15:16,595 views 11980 3580 Index page accessed
INFO 2023-08-30 09:15:16,596 basehttp 11980 3580 "GET / HTTP/1.1" 200 13
INFO 2023-08-30 09:44:13,536 autoreload 13956 7320 Watching for file changes with StatReloader
INFO 2023-08-30 09:44:27,456 views 13956 876 Index page accessed
INFO 2023-08-30 09:44:27,458 basehttp 13956 876 "GET / HTTP/1.1" 200 13
INFO 2023-08-30 09:44:32,141 views 13956 876 Index page accessed
INFO 2023-08-30 09:44:32,141 basehttp 13956 876 "GET / HTTP/1.1" 200 13
ERROR 2023-08-30 09:44:40,200 views 13956 876 Error in about page: division by zero
Traceback (most recent call last):
  File "C:\PY\django\myproject\myapp\views.py", line 16, in about
    result = 1 / 0
             ~~^~~
ZeroDivisionError: division by zero
INFO 2023-08-30 09:44:40,229 basehttp 13956 876 "GET /about/ HTTP/1.1" 200 27
INFO 2023-08-30 09:46:47,475 autoreload 13956 7320 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 09:46:48,424 autoreload 10024 12136 Watching for file changes with StatReloader
INFO 2023-08-30 09:46:59,095 basehttp 10024 12980 "GET /abouthw/ HTTP/1.1" 200 8
WARNING 2023-08-30 09:47:21,546 log 10024 12980 Not Found: /indexhw/
WARNING 2023-08-30 09:47:21,546 basehttp 10024 12980 "GET /indexhw/ HTTP/1.1" 404 2767
WARNING 2023-08-30 09:47:58,726 log 10024 12980 Not Found: /indexhw/
WARNING 2023-08-30 09:47:58,727 basehttp 10024 12980 "GET /indexhw/ HTTP/1.1" 404 2767
INFO 2023-08-30 09:47:59,214 autoreload 10024 12136 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 09:48:00,072 autoreload 4592 2868 Watching for file changes with StatReloader
WARNING 2023-08-30 09:48:03,375 log 4592 2132 Not Found: /indexhw/
WARNING 2023-08-30 09:48:03,376 basehttp 4592 2132 "GET /indexhw/ HTTP/1.1" 404 2765
WARNING 2023-08-30 09:48:04,956 log 4592 2132 Not Found: /indexhw/
WARNING 2023-08-30 09:48:04,957 basehttp 4592 2132 "GET /indexhw/ HTTP/1.1" 404 2765
INFO 2023-08-30 09:50:01,186 autoreload 4592 2868 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 09:50:02,004 autoreload 6672 6888 Watching for file changes with StatReloader
WARNING 2023-08-30 09:50:06,091 log 6672 9424 Not Found: /indexhw/
WARNING 2023-08-30 09:50:06,092 basehttp 6672 9424 "GET /indexhw/ HTTP/1.1" 404 2774
WARNING 2023-08-30 09:50:07,401 log 6672 9424 Not Found: /indexhw/
WARNING 2023-08-30 09:50:07,402 basehttp 6672 9424 "GET /indexhw/ HTTP/1.1" 404 2774
WARNING 2023-08-30 13:47:55,511 log 6672 5208 Not Found: /indexhw/
WARNING 2023-08-30 13:47:55,514 basehttp 6672 5208 "GET /indexhw/ HTTP/1.1" 404 2774
INFO 2023-08-30 14:05:44,957 autoreload 10944 10124 Watching for file changes with StatReloader
INFO 2023-08-30 14:05:49,369 views 10944 6752 Index page accessed
INFO 2023-08-30 14:05:49,371 basehttp 10944 6752 "GET / HTTP/1.1" 200 13
WARNING 2023-08-30 14:05:57,891 log 10944 2808 Not Found: /hw
WARNING 2023-08-30 14:05:57,892 basehttp 10944 2808 "GET /hw HTTP/1.1" 404 2518
WARNING 2023-08-30 14:06:11,490 log 10944 1636 Not Found: /hw/
WARNING 2023-08-30 14:06:11,491 basehttp 10944 1636 "GET /hw/ HTTP/1.1" 404 2757
INFO 2023-08-30 14:06:35,785 basehttp 10944 1636 "GET /hw/about HTTP/1.1" 301 0
INFO 2023-08-30 14:06:35,790 basehttp 10944 1296 "GET /hw/about/ HTTP/1.1" 200 8
WARNING 2023-08-30 14:06:45,671 log 10944 1296 Not Found: /hw/
WARNING 2023-08-30 14:06:45,672 basehttp 10944 1296 "GET /hw/ HTTP/1.1" 404 2757
INFO 2023-08-30 14:08:06,088 autoreload 10944 10124 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 14:08:07,005 autoreload 9032 13524 Watching for file changes with StatReloader
INFO 2023-08-30 14:08:12,874 basehttp 9032 14172 "GET /hw/ HTTP/1.1" 200 8
INFO 2023-08-30 14:08:26,717 basehttp 9032 14172 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:11:01,137 autoreload 9032 13524 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:11:02,037 autoreload 11140 7496 Watching for file changes with StatReloader
INFO 2023-08-30 14:11:12,490 autoreload 11140 7496 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:11:13,370 autoreload 6608 9648 Watching for file changes with StatReloader
INFO 2023-08-30 14:11:15,989 basehttp 6608 11348 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:11:20,976 basehttp 6608 11348 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:11:38,114 autoreload 6608 9648 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:11:38,932 autoreload 8200 1776 Watching for file changes with StatReloader
INFO 2023-08-30 14:11:41,816 basehttp 8200 15340 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:11:43,275 basehttp 8200 10208 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:13:18,598 autoreload 8200 1776 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 14:13:19,436 autoreload 9156 3384 Watching for file changes with StatReloader
INFO 2023-08-30 14:13:22,845 basehttp 9156 14108 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:13:29,684 basehttp 9156 14108 "GET /hw/ HTTP/1.1" 200 23
INFO 2023-08-30 14:16:21,797 autoreload 9156 3384 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:16:22,715 autoreload 12408 14580 Watching for file changes with StatReloader
INFO 2023-08-30 14:16:28,275 basehttp 12408 7684 "GET /hw/ HTTP/1.1" 200 282
INFO 2023-08-30 14:17:57,165 autoreload 12408 14580 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:17:57,975 autoreload 14608 9072 Watching for file changes with StatReloader
INFO 2023-08-30 14:18:02,495 basehttp 14608 10856 "GET /hw/ HTTP/1.1" 200 1844
WARNING 2023-08-30 14:18:02,904 log 14608 10856 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:18:02,905 log 14608 14636 Not Found: /hw/images/image.png
WARNING 2023-08-30 14:18:02,905 basehttp 14608 10856 "GET /hw/styles/style.css HTTP/1.1" 404 2797
WARNING 2023-08-30 14:18:02,906 basehttp 14608 14636 "GET /hw/images/image.png HTTP/1.1" 404 2797
WARNING 2023-08-30 14:18:16,385 log 14608 5216 Not Found: /hw/index.html
WARNING 2023-08-30 14:18:16,386 basehttp 14608 5216 "GET /hw/index.html HTTP/1.1" 404 2779
WARNING 2023-08-30 14:18:22,778 log 14608 5216 Not Found: /hw/catalog.html
WARNING 2023-08-30 14:18:22,779 basehttp 14608 5216 "GET /hw/catalog.html HTTP/1.1" 404 2785
INFO 2023-08-30 14:25:41,289 autoreload 14608 9072 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:25:42,220 autoreload 9904 14500 Watching for file changes with StatReloader
INFO 2023-08-30 14:29:53,798 autoreload 9904 14500 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:29:54,680 autoreload 1552 2764 Watching for file changes with StatReloader
INFO 2023-08-30 14:29:56,483 basehttp 1552 2888 "GET /hw/ HTTP/1.1" 200 2586
WARNING 2023-08-30 14:29:56,525 log 1552 11564 Not Found: /hw/images/image.png
WARNING 2023-08-30 14:29:56,527 log 1552 2888 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:29:56,527 basehttp 1552 11564 "GET /hw/images/image.png HTTP/1.1" 404 2797
WARNING 2023-08-30 14:29:56,528 basehttp 1552 2888 "GET /hw/styles/style.css HTTP/1.1" 404 2797
WARNING 2023-08-30 14:29:59,661 log 1552 2888 Not Found: /hw/hw/about/
WARNING 2023-08-30 14:29:59,662 basehttp 1552 2888 "GET /hw/hw/about/ HTTP/1.1" 404 2776
INFO 2023-08-30 14:30:23,664 autoreload 1552 2764 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:30:24,528 autoreload 672 14712 Watching for file changes with StatReloader
INFO 2023-08-30 14:30:28,430 basehttp 672 9104 "GET /hw/ HTTP/1.1" 200 2581
WARNING 2023-08-30 14:30:28,701 log 672 9536 Not Found: /hw/images/image.png
WARNING 2023-08-30 14:30:28,702 basehttp 672 9536 "GET /hw/images/image.png HTTP/1.1" 404 2797
WARNING 2023-08-30 14:30:28,703 log 672 9104 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:30:28,704 basehttp 672 9104 "GET /hw/styles/style.css HTTP/1.1" 404 2797
INFO 2023-08-30 14:30:29,065 basehttp 672 9104 "GET /hw/ HTTP/1.1" 200 2581
WARNING 2023-08-30 14:30:29,099 log 672 9104 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:30:29,100 log 672 9536 Not Found: /hw/images/image.png
WARNING 2023-08-30 14:30:29,101 basehttp 672 9104 "GET /hw/styles/style.css HTTP/1.1" 404 2797
WARNING 2023-08-30 14:30:29,101 basehttp 672 9536 "GET /hw/images/image.png HTTP/1.1" 404 2797
INFO 2023-08-30 14:30:32,750 basehttp 672 9536 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:30:39,749 basehttp 672 8836 "GET /hw/ HTTP/1.1" 200 2581
WARNING 2023-08-30 14:30:39,934 log 672 14308 Not Found: /hw/images/image.png
WARNING 2023-08-30 14:30:39,935 log 672 8836 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:30:39,936 basehttp 672 14308 "GET /hw/images/image.png HTTP/1.1" 404 2797
WARNING 2023-08-30 14:30:39,936 basehttp 672 8836 "GET /hw/styles/style.css HTTP/1.1" 404 2797
INFO 2023-08-30 14:30:40,691 basehttp 672 8836 "GET /hw/ HTTP/1.1" 200 2581
WARNING 2023-08-30 14:30:40,723 log 672 14308 Not Found: /hw/images/image.png
WARNING 2023-08-30 14:30:40,724 basehttp 672 14308 "GET /hw/images/image.png HTTP/1.1" 404 2797
WARNING 2023-08-30 14:30:40,726 log 672 8836 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:30:40,727 basehttp 672 8836 "GET /hw/styles/style.css HTTP/1.1" 404 2797
INFO 2023-08-30 14:31:35,322 autoreload 672 14712 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:31:36,178 autoreload 8804 3456 Watching for file changes with StatReloader
INFO 2023-08-30 14:32:23,294 autoreload 8804 3456 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:32:24,274 autoreload 9700 2616 Watching for file changes with StatReloader
INFO 2023-08-30 14:32:35,962 basehttp 9700 12384 "GET /hw/ HTTP/1.1" 200 2648
WARNING 2023-08-30 14:32:36,003 log 9700 12384 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:32:36,004 basehttp 9700 12384 "GET /hw/styles/style.css HTTP/1.1" 404 2797
INFO 2023-08-30 14:33:41,576 autoreload 9700 2616 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:33:42,393 autoreload 14624 13588 Watching for file changes with StatReloader
INFO 2023-08-30 14:33:44,431 basehttp 14624 10360 "GET /hw/ HTTP/1.1" 200 2657
WARNING 2023-08-30 14:33:44,461 log 14624 10360 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:33:44,462 basehttp 14624 10360 "GET /hw/styles/style.css HTTP/1.1" 404 2797
INFO 2023-08-30 14:34:56,309 autoreload 14624 13588 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:34:57,224 autoreload 2596 12800 Watching for file changes with StatReloader
INFO 2023-08-30 14:35:48,444 autoreload 2596 12800 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:35:49,398 autoreload 10324 12596 Watching for file changes with StatReloader
INFO 2023-08-30 14:35:58,747 autoreload 10324 12596 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:35:59,661 autoreload 8940 11340 Watching for file changes with StatReloader
INFO 2023-08-30 14:36:14,389 autoreload 8940 11340 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:36:15,274 autoreload 14220 10824 Watching for file changes with StatReloader
INFO 2023-08-30 14:37:45,137 autoreload 14220 10824 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:37:45,982 autoreload 8300 1716 Watching for file changes with StatReloader
INFO 2023-08-30 14:38:18,137 autoreload 8300 1716 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:38:19,165 autoreload 13000 9796 Watching for file changes with StatReloader
INFO 2023-08-30 14:41:29,765 autoreload 13000 9796 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:41:30,667 autoreload 13392 14748 Watching for file changes with StatReloader
INFO 2023-08-30 14:42:09,876 autoreload 13392 14748 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:42:10,930 autoreload 14632 6936 Watching for file changes with StatReloader
INFO 2023-08-30 14:44:12,398 autoreload 14632 6936 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:44:13,285 autoreload 12736 8208 Watching for file changes with StatReloader
INFO 2023-08-30 14:44:41,005 autoreload 12736 8208 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:44:42,041 autoreload 3644 14864 Watching for file changes with StatReloader
INFO 2023-08-30 14:44:47,163 basehttp 3644 3096 "GET /hw/ HTTP/1.1" 200 2873
WARNING 2023-08-30 14:44:47,489 log 3644 3096 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:44:47,489 basehttp 3644 3096 "GET /hw/styles/style.css HTTP/1.1" 404 2797
INFO 2023-08-30 14:46:10,099 basehttp 3644 5920 "GET /hw/about/ HTTP/1.1" 200 8
INFO 2023-08-30 14:46:10,979 autoreload 3644 14864 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:46:11,842 autoreload 4652 13164 Watching for file changes with StatReloader
INFO 2023-08-30 14:46:25,081 basehttp 4652 14980 "GET /hw/ HTTP/1.1" 200 2857
WARNING 2023-08-30 14:46:25,108 log 4652 14980 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:46:25,110 basehttp 4652 14980 "GET /hw/styles/style.css HTTP/1.1" 404 2797
INFO 2023-08-30 14:49:31,972 autoreload 4652 13164 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:49:32,872 autoreload 6912 12080 Watching for file changes with StatReloader
INFO 2023-08-30 14:53:35,628 autoreload 6912 12080 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 14:53:36,602 autoreload 14644 9880 Watching for file changes with StatReloader
INFO 2023-08-30 14:54:58,384 autoreload 14644 9880 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 14:54:59,366 autoreload 13928 3432 Watching for file changes with StatReloader
INFO 2023-08-30 14:56:43,847 autoreload 13928 3432 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 14:56:44,687 autoreload 12644 1944 Watching for file changes with StatReloader
INFO 2023-08-30 14:57:09,647 autoreload 12644 1944 C:\PY\django\myproject\hw_1_app\urls.py changed, reloading.
INFO 2023-08-30 14:57:10,449 autoreload 9648 10244 Watching for file changes with StatReloader
INFO 2023-08-30 14:57:18,136 basehttp 9648 9376 "GET /hw/ HTTP/1.1" 200 3131
WARNING 2023-08-30 14:57:18,170 log 9648 9376 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:57:18,171 basehttp 9648 9376 "GET /hw/styles/style.css HTTP/1.1" 404 2805
INFO 2023-08-30 14:57:23,925 basehttp 9648 11932 "GET /hw/ HTTP/1.1" 200 3131
WARNING 2023-08-30 14:57:23,947 log 9648 11932 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:57:23,948 basehttp 9648 11932 "GET /hw/styles/style.css HTTP/1.1" 404 2805
INFO 2023-08-30 14:57:25,028 basehttp 9648 11932 "GET /hw/ HTTP/1.1" 200 3131
WARNING 2023-08-30 14:57:25,049 log 9648 11932 Not Found: /hw/styles/style.css
WARNING 2023-08-30 14:57:25,049 basehttp 9648 11932 "GET /hw/styles/style.css HTTP/1.1" 404 2805
INFO 2023-08-30 15:00:08,955 autoreload 9648 10244 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:00:09,851 autoreload 12012 7660 Watching for file changes with StatReloader
INFO 2023-08-30 15:00:12,870 basehttp 12012 8532 "GET /hw/ HTTP/1.1" 200 3104
WARNING 2023-08-30 15:00:12,905 log 12012 8532 Not Found: /hw/styles/style.css
WARNING 2023-08-30 15:00:12,906 basehttp 12012 8532 "GET /hw/styles/style.css HTTP/1.1" 404 2805
WARNING 2023-08-30 15:00:22,603 log 12012 1428 Not Found: /hw/hometask/
WARNING 2023-08-30 15:00:22,604 basehttp 12012 1428 "GET /hw/hometask/ HTTP/1.1" 404 2784
INFO 2023-08-30 15:00:33,567 autoreload 12012 7660 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:00:34,388 autoreload 9716 13816 Watching for file changes with StatReloader
WARNING 2023-08-30 15:00:38,811 log 9716 12664 Not Found: /hw/hometask/
WARNING 2023-08-30 15:00:38,812 basehttp 9716 12664 "GET /hw/hometask/ HTTP/1.1" 404 2784
INFO 2023-08-30 15:01:25,336 basehttp 9716 14108 "GET /hw/home_task/ HTTP/1.1" 200 675
WARNING 2023-08-30 15:01:43,072 log 9716 15212 Not Found: /hw/hometask/
WARNING 2023-08-30 15:01:43,073 basehttp 9716 15212 "GET /hw/hometask/ HTTP/1.1" 404 2784
WARNING 2023-08-30 15:01:50,933 log 9716 14516 Not Found: /hw/hometask/
WARNING 2023-08-30 15:01:50,934 basehttp 9716 14516 "GET /hw/hometask/ HTTP/1.1" 404 2784
INFO 2023-08-30 15:04:24,492 autoreload 13920 13576 Watching for file changes with StatReloader
INFO 2023-08-30 15:04:31,482 basehttp 13920 8108 "GET /hw/ HTTP/1.1" 200 3105
WARNING 2023-08-30 15:04:31,740 log 13920 8108 Not Found: /hw/styles/style.css
WARNING 2023-08-30 15:04:31,741 basehttp 13920 8108 "GET /hw/styles/style.css HTTP/1.1" 404 2805
INFO 2023-08-30 15:04:32,221 basehttp 13920 8108 "GET /hw/ HTTP/1.1" 200 3105
WARNING 2023-08-30 15:04:32,247 log 13920 8108 Not Found: /hw/styles/style.css
WARNING 2023-08-30 15:04:32,247 basehttp 13920 8108 "GET /hw/styles/style.css HTTP/1.1" 404 2805
INFO 2023-08-30 15:04:35,893 basehttp 13920 7568 "GET /hw/home_task/ HTTP/1.1" 200 675
INFO 2023-08-30 15:05:48,052 autoreload 13920 13576 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:05:48,998 autoreload 13296 12408 Watching for file changes with StatReloader
INFO 2023-08-30 15:06:00,055 basehttp 13296 12044 "GET /hw/home_task/ HTTP/1.1" 200 675
INFO 2023-08-30 15:12:03,731 autoreload 13296 12408 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:12:04,581 autoreload 13172 12488 Watching for file changes with StatReloader
INFO 2023-08-30 15:12:23,758 autoreload 10648 4000 Watching for file changes with StatReloader
INFO 2023-08-30 15:12:36,003 basehttp 10648 10476 "GET /hw/ HTTP/1.1" 200 2797
WARNING 2023-08-30 15:12:36,207 log 10648 10476 Not Found: /hw/styles/style.css
WARNING 2023-08-30 15:12:36,208 basehttp 10648 10476 "GET /hw/styles/style.css HTTP/1.1" 404 2805
INFO 2023-08-30 15:12:37,229 basehttp 10648 10476 "GET /hw/ HTTP/1.1" 200 2797
WARNING 2023-08-30 15:12:37,257 log 10648 10476 Not Found: /hw/styles/style.css
WARNING 2023-08-30 15:12:37,257 basehttp 10648 10476 "GET /hw/styles/style.css HTTP/1.1" 404 2805
INFO 2023-08-30 15:14:20,310 autoreload 10648 4000 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:14:21,146 autoreload 844 6944 Watching for file changes with StatReloader
INFO 2023-08-30 15:14:29,491 basehttp 844 13944 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:14:34,322 basehttp 844 13944 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:14:42,129 basehttp 844 10448 "GET /hw/home_task/ HTTP/1.1" 200 675
INFO 2023-08-30 15:14:53,737 basehttp 844 10540 "GET /hw/home_task/ HTTP/1.1" 200 675
INFO 2023-08-30 15:17:43,545 autoreload 844 6944 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:17:44,449 autoreload 2368 6912 Watching for file changes with StatReloader
INFO 2023-08-30 15:17:47,642 basehttp 2368 2996 "GET /hw/home_task/ HTTP/1.1" 200 759
INFO 2023-08-30 15:18:47,738 autoreload 2368 6912 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:18:48,574 autoreload 11280 8748 Watching for file changes with StatReloader
INFO 2023-08-30 15:18:50,782 basehttp 11280 10200 "GET /hw/home_task/ HTTP/1.1" 200 748
INFO 2023-08-30 15:18:53,786 basehttp 11280 10200 "GET /hw/home_task/ HTTP/1.1" 200 748
INFO 2023-08-30 15:18:56,546 basehttp 11280 4684 "GET /hw/home_task/ HTTP/1.1" 200 748
INFO 2023-08-30 15:18:57,579 basehttp 11280 4684 "GET /hw/home_task/ HTTP/1.1" 200 748
INFO 2023-08-30 15:19:17,568 autoreload 11280 8748 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:19:18,398 autoreload 13908 2148 Watching for file changes with StatReloader
INFO 2023-08-30 15:19:22,131 basehttp 13908 10368 "GET /hw/home_task/ HTTP/1.1" 200 751
WARNING 2023-08-30 15:19:23,788 log 13908 10368 Not Found: /hw/home_task/hw/
WARNING 2023-08-30 15:19:23,789 basehttp 13908 10368 "GET /hw/home_task/hw/ HTTP/1.1" 404 2796
INFO 2023-08-30 15:19:52,685 autoreload 13908 2148 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:19:53,491 autoreload 12660 12000 Watching for file changes with StatReloader
INFO 2023-08-30 15:20:14,158 basehttp 12660 11808 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:20:14,932 basehttp 12660 11808 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:20:17,639 basehttp 12660 9884 "GET /hw/home_task/ HTTP/1.1" 200 749
INFO 2023-08-30 15:20:19,465 views 12660 9884 Index page accessed
INFO 2023-08-30 15:20:19,466 basehttp 12660 9884 "GET / HTTP/1.1" 200 13
INFO 2023-08-30 15:20:39,473 autoreload 12660 12000 C:\PY\django\myproject\hw_1_app\views.py changed, reloading.
INFO 2023-08-30 15:20:40,334 autoreload 5348 9616 Watching for file changes with StatReloader
INFO 2023-08-30 15:20:47,793 basehttp 5348 14300 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:20:48,692 basehttp 5348 14300 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:20:52,867 basehttp 5348 14300 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-08-30 15:20:54,671 basehttp 5348 14300 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:20:58,663 basehttp 5348 7176 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-08-30 15:20:59,975 basehttp 5348 7176 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:24:38,819 autoreload 3012 2288 Watching for file changes with StatReloader
INFO 2023-08-30 15:24:43,840 views 3012 14152 Homework index page -> access
INFO 2023-08-30 15:24:43,841 basehttp 3012 14152 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:24:48,464 views 3012 10648 Home task page -> access
INFO 2023-08-30 15:24:48,465 basehttp 3012 10648 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-08-30 15:24:56,668 views 3012 10648 Homework index page -> access
INFO 2023-08-30 15:24:56,668 basehttp 3012 10648 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:25:17,274 views 3012 7028 Home task page -> access
INFO 2023-08-30 15:25:17,275 basehttp 3012 7028 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-08-30 15:25:26,752 views 3012 7028 Homework index page -> access
INFO 2023-08-30 15:25:26,753 basehttp 3012 7028 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:25:27,842 views 3012 10008 Homework index page -> access
INFO 2023-08-30 15:25:27,843 basehttp 3012 10008 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:25:37,119 views 3012 10008 Home task page -> access
INFO 2023-08-30 15:25:37,120 basehttp 3012 10008 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-08-30 15:25:42,920 views 3012 12940 Homework index page -> access
INFO 2023-08-30 15:25:42,921 basehttp 3012 12940 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:25:47,561 views 3012 4216 Homework index page -> access
INFO 2023-08-30 15:25:47,561 basehttp 3012 4216 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-30 15:25:56,258 views 3012 4216 Home task page -> access
INFO 2023-08-30 15:25:56,259 basehttp 3012 4216 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-08-30 15:26:04,814 views 3012 12840 Homework index page -> access
INFO 2023-08-30 15:26:04,815 basehttp 3012 12840 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-31 09:16:58,901 autoreload 12916 11344 Watching for file changes with StatReloader
INFO 2023-08-31 09:17:23,511 basehttp 12916 7424 "GET / HTTP/1.1" 200 13
WARNING 2023-08-31 09:17:24,018 log 12916 7424 Not Found: /favicon.ico
WARNING 2023-08-31 09:17:24,018 basehttp 12916 7424 "GET /favicon.ico HTTP/1.1" 404 2648
INFO 2023-08-31 09:17:32,714 basehttp 12916 7424 "GET /s1 HTTP/1.1" 301 0
INFO 2023-08-31 09:17:32,722 basehttp 12916 6796 "GET /s1/ HTTP/1.1" 200 16
INFO 2023-08-31 09:17:47,283 basehttp 12916 6796 "GET /s1/heads HTTP/1.1" 301 0
ERROR 2023-08-31 09:17:47,549 log 12916 12768 Internal Server Error: /s1/heads/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
ERROR 2023-08-31 09:17:47,557 basehttp 12916 12768 "GET /s1/heads/ HTTP/1.1" 500 63292
ERROR 2023-08-31 09:18:32,813 log 12916 12768 Internal Server Error: /s1/cube/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
ERROR 2023-08-31 09:18:32,821 basehttp 12916 12768 "GET /s1/cube/ HTTP/1.1" 500 63244
INFO 2023-08-31 09:20:57,342 autoreload 12916 11344 C:\PY\django\myproject\s1app\views.py changed, reloading.
INFO 2023-08-31 09:20:59,243 autoreload 2808 6856 Watching for file changes with StatReloader
INFO 2023-08-31 09:21:02,876 basehttp 2808 9084 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 09:21:05,294 basehttp 2808 9084 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 09:21:06,110 basehttp 2808 9084 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 09:21:06,614 basehttp 2808 9084 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 09:21:07,107 basehttp 2808 9084 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 09:21:07,670 basehttp 2808 9084 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 09:21:15,648 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:18,030 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 1
INFO 2023-08-31 09:21:18,750 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:19,254 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:19,726 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:20,126 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:20,467 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:20,709 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:20,926 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 3
INFO 2023-08-31 09:21:21,139 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:21,340 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:21,509 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:21,708 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:21,888 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:22,072 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:22,225 basehttp 2808 9084 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 09:21:30,274 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:32,726 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:33,222 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:33,478 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:33,708 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:34,154 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:34,611 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:35,006 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:35,223 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:35,590 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:35,856 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:21:36,210 basehttp 2808 9084 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 09:42:38,059 autoreload 2808 6856 C:\PY\django\myproject\my_project\settings.py changed, reloading.
INFO 2023-08-31 09:42:47,601 autoreload 11888 9708 Watching for file changes with StatReloader
INFO 2023-08-31 09:44:51,684 autoreload 11888 9708 C:\PY\django\myproject\my_project\settings.py changed, reloading.
INFO 2023-08-31 10:02:55,589 autoreload 14048 2256 Watching for file changes with StatReloader
INFO 2023-08-31 10:03:02,676 basehttp 14048 14056 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:03:03,545 basehttp 14048 14056 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:03:07,550 basehttp 14048 14056 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:03:10,790 basehttp 14048 14056 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:03:11,352 basehttp 14048 12948 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:03:20,445 basehttp 14048 12948 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:03:22,930 basehttp 14048 13336 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:03:23,482 basehttp 14048 13336 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:03:23,736 basehttp 14048 13336 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:03:23,920 basehttp 14048 13336 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:03:24,105 basehttp 14048 13336 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:03:24,282 basehttp 14048 13336 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:03:31,242 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:32,619 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:32,872 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:33,057 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:33,257 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:33,462 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:33,721 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:34,287 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:34,481 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:03:34,730 basehttp 14048 12612 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:52,126 autoreload 10356 12520 Watching for file changes with StatReloader
INFO 2023-08-31 10:08:55,938 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:56,934 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:57,340 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:57,556 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:57,781 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:58,004 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:58,741 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:59,481 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:08:59,700 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:09:00,308 basehttp 10356 14708 "GET /s1/number/ HTTP/1.1" 200 2
INFO 2023-08-31 10:09:09,634 basehttp 10356 10292 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:11,925 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:12,125 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:12,317 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:12,500 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:12,688 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:12,852 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:13,013 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:13,357 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:13,557 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:13,701 basehttp 10356 7252 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 10:09:20,761 basehttp 10356 7252 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:22,845 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:23,045 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:23,241 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:23,618 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:23,809 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:23,996 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:24,176 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:24,352 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:24,521 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:24,874 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:25,068 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:25,265 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:25,466 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:25,688 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:25,872 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:26,102 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:26,641 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:26,840 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 10:09:27,060 basehttp 10356 14008 "GET /s1/heads/ HTTP/1.1" 200 5
INFO 2023-08-31 18:57:57,714 autoreload 9228 4824 Watching for file changes with StatReloader
INFO 2023-08-31 18:58:01,494 basehttp 9228 8012 "GET / HTTP/1.1" 200 13
WARNING 2023-08-31 18:58:01,539 log 9228 8012 Not Found: /favicon.ico
WARNING 2023-08-31 18:58:01,539 basehttp 9228 8012 "GET /favicon.ico HTTP/1.1" 404 2648
INFO 2023-08-31 18:58:13,195 basehttp 9228 8012 "GET /s1/ HTTP/1.1" 200 16
INFO 2023-08-31 18:58:22,095 basehttp 9228 8012 "GET /s1/cube HTTP/1.1" 301 0
INFO 2023-08-31 18:58:22,097 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:26,346 basehttp 9228 6024 "GET /s1/ HTTP/1.1" 200 16
INFO 2023-08-31 18:58:32,108 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:33,777 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:34,377 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:34,673 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:34,873 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:35,072 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:35,265 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:35,449 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:35,625 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:35,785 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 18:58:36,017 basehttp 9228 6024 "GET /s1/cube/ HTTP/1.1" 200 1
WARNING 2023-08-31 18:59:10,191 log 9228 6024 Not Found: /s1/hw
WARNING 2023-08-31 18:59:10,191 basehttp 9228 6024 "GET /s1/hw HTTP/1.1" 404 3205
INFO 2023-08-31 18:59:50,762 basehttp 9228 6024 "GET /hw HTTP/1.1" 301 0
INFO 2023-08-31 18:59:50,764 basehttp 9228 8036 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-31 18:59:58,530 basehttp 9228 8036 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-08-31 19:00:04,794 basehttp 9228 8036 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-31 19:00:06,289 basehttp 9228 8036 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-08-31 19:00:12,473 basehttp 9228 8036 "GET /hw/home_task/ HTTP/1.1" 200 752
INFO 2023-09-01 08:29:48,497 autoreload 1072 12044 Watching for file changes with StatReloader
INFO 2023-09-01 08:30:05,447 autoreload 1072 12044 C:\PY\django\myproject\s2app\views.py changed, reloading.
INFO 2023-09-01 08:30:11,091 autoreload 8632 7312 Watching for file changes with StatReloader
INFO 2023-09-01 08:30:15,187 basehttp 8632 4492 "GET / HTTP/1.1" 200 13
WARNING 2023-09-01 08:30:15,617 log 8632 4492 Not Found: /favicon.ico
WARNING 2023-09-01 08:30:15,617 basehttp 8632 4492 "GET /favicon.ico HTTP/1.1" 404 2751
INFO 2023-09-01 08:30:21,901 basehttp 8632 4492 "GET /s2 HTTP/1.1" 301 0
ERROR 2023-09-01 08:30:22,378 log 8632 2196 Internal Server Error: /s2/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: s2app_gamemodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\s2app\views.py", line 13, in index
    game.save()
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\PY\django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: s2app_gamemodel
ERROR 2023-09-01 08:30:22,386 basehttp 8632 2196 "GET /s2/ HTTP/1.1" 500 143770
INFO 2023-09-01 08:49:54,606 autoreload 8340 896 Watching for file changes with StatReloader
INFO 2023-09-01 08:49:59,066 basehttp 8340 7080 "GET / HTTP/1.1" 200 13
INFO 2023-09-01 08:50:05,754 basehttp 8340 7080 "GET /s2/ HTTP/1.1" 200 80
INFO 2023-09-01 08:50:09,123 basehttp 8340 7080 "GET /s2/ HTTP/1.1" 200 80
INFO 2023-09-01 08:50:10,297 basehttp 8340 7080 "GET /s2/ HTTP/1.1" 200 80
INFO 2023-09-01 08:50:11,234 basehttp 8340 7080 "GET /s2/ HTTP/1.1" 200 80
INFO 2023-09-01 08:50:11,909 basehttp 8340 7080 "GET /s2/ HTTP/1.1" 200 80
INFO 2023-09-01 08:50:12,564 basehttp 8340 7080 "GET /s2/ HTTP/1.1" 200 80
INFO 2023-09-01 08:50:13,133 basehttp 8340 7080 "GET /s2/ HTTP/1.1" 200 80
WARNING 2023-09-01 08:50:50,083 log 8340 7080 Not Found: /s2/last_games
WARNING 2023-09-01 08:50:50,083 basehttp 8340 7080 "GET /s2/last_games HTTP/1.1" 404 3164
INFO 2023-09-01 08:51:09,804 basehttp 8340 7080 "GET /s2/last HTTP/1.1" 301 0
INFO 2023-09-01 08:51:09,812 basehttp 8340 1928 "GET /s2/last/ HTTP/1.1" 200 420
WARNING 2023-09-01 08:51:23,294 log 8340 1928 Not Found: /s2/autor
WARNING 2023-09-01 08:51:23,294 basehttp 8340 1928 "GET /s2/autor HTTP/1.1" 404 3149
INFO 2023-09-01 08:51:30,742 basehttp 8340 8768 "GET /s2/author HTTP/1.1" 301 0
INFO 2023-09-01 08:51:30,750 basehttp 8340 14036 "GET /s2/author/ HTTP/1.1" 200 100
INFO 2023-09-04 09:44:35,918 autoreload 8696 1896 Watching for file changes with StatReloader
INFO 2023-09-04 09:44:38,154 basehttp 8696 12512 "GET / HTTP/1.1" 200 13
INFO 2023-09-04 09:44:48,736 basehttp 8696 6584 "GET /hello HTTP/1.1" 301 0
INFO 2023-09-04 09:44:48,740 basehttp 8696 4084 "GET /hello/ HTTP/1.1" 200 26
INFO 2023-09-04 09:44:57,165 basehttp 8696 4084 "GET /hello2/ HTTP/1.1" 200 23
INFO 2023-09-04 09:46:30,118 autoreload 8696 1896 C:\PY\django\myproject\my_project\urls.py changed, reloading.
INFO 2023-09-04 09:46:30,998 autoreload 12724 8960 Watching for file changes with StatReloader
WARNING 2023-09-04 09:46:33,949 log 12724 11296 Not Found: /hello2/
WARNING 2023-09-04 09:46:33,950 basehttp 12724 11296 "GET /hello2/ HTTP/1.1" 404 2844
INFO 2023-09-04 09:46:42,664 basehttp 12724 7136 "GET /les3/hello2/ HTTP/1.1" 200 23
INFO 2023-09-04 09:47:35,813 autoreload 12724 8960 C:\PY\django\myproject\myapp3\urls.py changed, reloading.
INFO 2023-09-04 09:47:36,801 autoreload 12356 152 Watching for file changes with StatReloader
INFO 2023-09-04 09:47:46,244 autoreload 12356 152 C:\PY\django\myproject\myapp3\urls.py changed, reloading.
INFO 2023-09-04 09:47:47,174 autoreload 11424 11948 Watching for file changes with StatReloader
INFO 2023-09-04 09:48:39,886 autoreload 11424 11948 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 09:49:37,526 autoreload 11852 10924 Watching for file changes with StatReloader
INFO 2023-09-04 09:50:50,589 autoreload 11852 10924 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 09:50:51,698 autoreload 14892 264 Watching for file changes with StatReloader
INFO 2023-09-04 09:51:17,714 autoreload 14892 264 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 09:51:18,668 autoreload 15072 824 Watching for file changes with StatReloader
INFO 2023-09-04 09:52:59,645 autoreload 15072 824 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 09:53:00,527 autoreload 10340 11780 Watching for file changes with StatReloader
INFO 2023-09-04 09:53:23,479 basehttp 10340 13380 "GET /les3/posts/2022/6/python/ HTTP/1.1" 200 360
INFO 2023-09-04 09:53:35,061 basehttp 10340 13380 "GET /les3/posts/2022/6/ HTTP/1.1" 200 21
INFO 2023-09-04 09:53:42,072 basehttp 10340 13380 "GET /les3/posts/2022/ HTTP/1.1" 200 19
INFO 2023-09-04 10:17:31,992 autoreload 10340 11780 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 10:17:33,194 autoreload 5504 9712 Watching for file changes with StatReloader
INFO 2023-09-04 10:18:32,263 autoreload 5504 9712 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 10:18:33,399 autoreload 7540 13196 Watching for file changes with StatReloader
WARNING 2023-09-04 10:18:56,572 log 7540 12104 Not Found: /les3/
WARNING 2023-09-04 10:18:56,573 basehttp 7540 12104 "GET /les3/ HTTP/1.1" 404 3715
INFO 2023-09-04 10:18:57,171 autoreload 7540 13196 C:\PY\django\myproject\myapp3\urls.py changed, reloading.
INFO 2023-09-04 10:18:58,156 autoreload 5496 10420 Watching for file changes with StatReloader
INFO 2023-09-04 10:19:20,116 basehttp 5496 9364 "GET /les3/ HTTP/1.1" 200 175
INFO 2023-09-04 10:22:32,819 autoreload 5496 10420 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 10:22:33,718 autoreload 8332 8316 Watching for file changes with StatReloader
INFO 2023-09-04 10:23:05,746 autoreload 8332 8316 C:\PY\django\myproject\myapp3\urls.py changed, reloading.
INFO 2023-09-04 10:23:06,704 autoreload 1888 13236 Watching for file changes with StatReloader
INFO 2023-09-04 10:25:00,603 autoreload 1888 13236 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 10:25:01,553 autoreload 4992 8376 Watching for file changes with StatReloader
INFO 2023-09-04 10:25:18,568 autoreload 4992 8376 C:\PY\django\myproject\myapp3\urls.py changed, reloading.
INFO 2023-09-04 10:25:19,635 autoreload 13268 7264 Watching for file changes with StatReloader
INFO 2023-09-04 10:32:52,636 autoreload 13268 7264 C:\PY\django\myproject\my_project\settings.py changed, reloading.
INFO 2023-09-04 10:32:53,835 autoreload 5388 4880 Watching for file changes with StatReloader
INFO 2023-09-04 10:34:29,517 autoreload 5388 4880 C:\PY\django\myproject\myapp3\models.py changed, reloading.
INFO 2023-09-04 10:34:30,578 autoreload 13284 3432 Watching for file changes with StatReloader
INFO 2023-09-04 10:55:42,611 autoreload 8900 12452 Watching for file changes with StatReloader
INFO 2023-09-04 10:56:07,109 autoreload 8900 12452 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 10:56:08,065 autoreload 4892 5476 Watching for file changes with StatReloader
INFO 2023-09-04 10:56:14,547 autoreload 9816 2292 Watching for file changes with StatReloader
INFO 2023-09-04 10:56:34,271 autoreload 9816 2292 C:\PY\django\myproject\myapp3\views.py changed, reloading.
INFO 2023-09-04 10:56:38,981 autoreload 14852 10176 Watching for file changes with StatReloader
INFO 2023-09-04 10:56:44,717 basehttp 14852 10416 "GET / HTTP/1.1" 200 13
INFO 2023-09-04 10:56:54,125 basehttp 14852 10872 "GET /les3 HTTP/1.1" 301 0
INFO 2023-09-04 10:56:54,228 basehttp 14852 2268 "GET /les3/ HTTP/1.1" 200 175
WARNING 2023-09-04 10:57:14,713 log 14852 13168 Not Found: /les3/author_posts/5
WARNING 2023-09-04 10:57:14,715 basehttp 14852 13168 "GET /les3/author_posts/5 HTTP/1.1" 404 4666
INFO 2023-09-04 10:57:33,229 basehttp 14852 13908 "GET /les3/author/5 HTTP/1.1" 301 0
INFO 2023-09-04 10:57:33,265 basehttp 14852 14428 "GET /les3/author/5/ HTTP/1.1" 200 1225
INFO 2023-09-04 10:57:36,430 basehttp 14852 14428 "GET /les3/post/34/ HTTP/1.1" 200 591
INFO 2023-09-05 16:20:20,316 autoreload 12287 140660356145152 Watching for file changes with StatReloader
INFO 2023-09-05 16:21:06,912 autoreload 12448 140402560884736 Watching for file changes with StatReloader
INFO 2023-09-05 16:21:10,663 basehttp 12448 140402508166720 "GET / HTTP/1.1" 200 13
WARNING 2023-09-05 16:21:10,711 log 12448 140402508166720 Not Found: /favicon.ico
WARNING 2023-09-05 16:21:10,712 basehttp 12448 140402508166720 "GET /favicon.ico HTTP/1.1" 404 2961
INFO 2023-09-05 16:21:27,804 basehttp 12448 140402508166720 "GET /les4/user/add HTTP/1.1" 301 0
INFO 2023-09-05 16:21:27,814 basehttp 12448 140402499774016 "GET /les4/user/add/ HTTP/1.1" 200 692
INFO 2023-09-05 16:23:13,398 basehttp 12448 140402499774016 "GET /les4/user/add/ HTTP/1.1" 200 716
INFO 2023-09-05 16:24:37,283 basehttp 12448 140402499774016 "GET /les4/user/add/ HTTP/1.1" 200 941
INFO 2023-09-05 16:25:32,915 basehttp 12448 140402499774016 "POST /les4/user/add/ HTTP/1.1" 200 988
INFO 2023-09-05 16:26:11,380 basehttp 12448 140402499774016 "POST /les4/user/add/ HTTP/1.1" 200 992
INFO 2023-09-05 16:31:44,120 autoreload 12448 140402560884736 /home/alevtin/PycharmProjects/django/myproject/myapp4/forms.py changed, reloading.
INFO 2023-09-05 16:31:44,353 autoreload 14245 139756826148864 Watching for file changes with StatReloader
INFO 2023-09-05 16:34:52,317 autoreload 14245 139756826148864 /home/alevtin/PycharmProjects/django/myproject/myapp4/urls.py changed, reloading.
INFO 2023-09-05 16:34:52,534 autoreload 14737 140067755577344 Watching for file changes with StatReloader
INFO 2023-09-05 16:35:26,660 basehttp 14737 140067703092800 "GET /les4/forms HTTP/1.1" 301 0
INFO 2023-09-05 16:35:26,675 basehttp 14737 140067694700096 "GET /les4/forms/ HTTP/1.1" 200 1477
INFO 2023-09-05 16:36:00,382 basehttp 14737 140067694700096 "POST /les4/forms/ HTTP/1.1" 200 1571
INFO 2023-09-05 16:44:52,752 autoreload 14737 140067755577344 /home/alevtin/PycharmProjects/django/myproject/myapp4/forms.py changed, reloading.
INFO 2023-09-05 16:44:52,983 autoreload 16127 140616211300352 Watching for file changes with StatReloader
INFO 2023-09-05 16:44:57,696 basehttp 16127 140616088417856 "POST /les4/forms/ HTTP/1.1" 200 2250
INFO 2023-09-05 16:45:29,018 basehttp 16127 140616088417856 "POST /les4/forms/ HTTP/1.1" 200 2204
INFO 2023-09-05 16:47:19,805 autoreload 16127 140616211300352 /home/alevtin/PycharmProjects/django/myproject/myapp4/forms.py changed, reloading.
INFO 2023-09-05 16:47:20,041 autoreload 16467 140523068149760 Watching for file changes with StatReloader
INFO 2023-09-05 16:47:23,046 basehttp 16467 140522941314624 "POST /les4/forms/ HTTP/1.1" 200 2204
INFO 2023-09-05 16:52:53,781 autoreload 16467 140523068149760 /home/alevtin/PycharmProjects/django/myproject/myapp4/forms.py changed, reloading.
INFO 2023-09-05 16:52:53,998 autoreload 17222 140687172546560 Watching for file changes with StatReloader
INFO 2023-09-05 16:53:55,432 autoreload 17222 140687172546560 /home/alevtin/PycharmProjects/django/myproject/myapp4/models.py changed, reloading.
INFO 2023-09-05 16:53:55,655 autoreload 17376 140120570179584 Watching for file changes with StatReloader
INFO 2023-09-05 16:59:16,261 autoreload 18140 140170805633024 Watching for file changes with StatReloader
INFO 2023-09-05 16:59:27,296 basehttp 18140 140170682693184 "GET /les4/user HTTP/1.1" 301 0
INFO 2023-09-05 16:59:27,306 basehttp 18140 140170674300480 "GET /les4/user/ HTTP/1.1" 200 980
INFO 2023-09-05 17:02:10,714 basehttp 18140 140170674300480 "GET /les4/user/ HTTP/1.1" 200 919
INFO 2023-09-05 17:02:46,814 basehttp 18140 140170674300480 "POST /les4/user/ HTTP/1.1" 200 1059
INFO 2023-09-05 17:03:08,264 basehttp 18140 140170674300480 "POST /les4/user/ HTTP/1.1" 200 976
INFO 2023-09-05 17:07:06,761 autoreload 18140 140170805633024 /home/alevtin/PycharmProjects/django/myproject/myapp4/forms.py changed, reloading.
INFO 2023-09-05 17:07:06,986 autoreload 19307 140324387414016 Watching for file changes with StatReloader
INFO 2023-09-05 17:07:34,233 autoreload 19307 140324387414016 /home/alevtin/PycharmProjects/django/myproject/my_project/settings.py changed, reloading.
INFO 2023-09-05 17:07:34,456 autoreload 19395 140175838089216 Watching for file changes with StatReloader
INFO 2023-09-05 17:09:47,249 autoreload 19395 140175838089216 /home/alevtin/PycharmProjects/django/myproject/myapp4/views.py changed, reloading.
INFO 2023-09-05 17:09:47,468 autoreload 19687 140350440476672 Watching for file changes with StatReloader
INFO 2023-09-05 17:10:53,923 autoreload 19687 140350440476672 /home/alevtin/PycharmProjects/django/myproject/myapp4/urls.py changed, reloading.
INFO 2023-09-05 17:10:54,154 autoreload 19883 139974290350080 Watching for file changes with StatReloader
INFO 2023-09-05 17:12:48,750 basehttp 19883 139974237222464 "GET /les4/upload HTTP/1.1" 301 0
ERROR 2023-09-05 17:12:48,773 log 19883 139974228829760 Internal Server Error: /les4/upload/
Traceback (most recent call last):
  File "/home/alevtin/PycharmProjects/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/PycharmProjects/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/PycharmProjects/django/myproject/myapp4/views.py", line 57, in upload_image
    if form.is_valid():
UnboundLocalError: local variable 'form' referenced before assignment
ERROR 2023-09-05 17:12:48,774 basehttp 19883 139974228829760 "GET /les4/upload/ HTTP/1.1" 500 67159
INFO 2023-09-05 17:13:34,061 autoreload 19883 139974290350080 /home/alevtin/PycharmProjects/django/myproject/myapp4/views.py changed, reloading.
INFO 2023-09-05 17:13:34,280 autoreload 20328 139963076702208 Watching for file changes with StatReloader
INFO 2023-09-05 17:13:35,224 basehttp 20328 139963023750720 "GET /les4/upload/ HTTP/1.1" 200 624
INFO 2023-09-05 17:14:11,811 basehttp 20328 139963023750720 "POST /les4/upload/ HTTP/1.1" 200 624
INFO 2023-09-06 20:30:59,020 autoreload 1404 13116 Watching for file changes with StatReloader
INFO 2023-09-06 20:31:01,800 basehttp 1404 10236 "GET / HTTP/1.1" 200 13
WARNING 2023-09-06 20:31:01,880 log 1404 10236 Not Found: /favicon.ico
WARNING 2023-09-06 20:31:01,880 basehttp 1404 10236 "GET /favicon.ico HTTP/1.1" 404 3272
INFO 2023-09-06 20:31:08,336 basehttp 1404 10236 "GET /hw HTTP/1.1" 301 0
INFO 2023-09-06 20:31:08,339 basehttp 1404 7512 "GET /hw/ HTTP/1.1" 200 2710
INFO 2023-09-06 20:31:10,095 basehttp 1404 7512 "GET /hw3 HTTP/1.1" 301 0
INFO 2023-09-06 20:31:10,097 basehttp 1404 3588 "GET /hw3/ HTTP/1.1" 200 1665
INFO 2023-09-06 20:31:42,374 basehttp 1404 3588 "GET /hw3/clients HTTP/1.1" 301 0
INFO 2023-09-06 20:31:42,378 basehttp 1404 9512 "GET /hw3/clients/ HTTP/1.1" 200 0
INFO 2023-09-06 20:46:25,925 autoreload 7196 14512 Watching for file changes with StatReloader
INFO 2023-09-06 20:46:28,620 basehttp 7196 9756 "GET /hw3/clients/ HTTP/1.1" 200 421
INFO 2023-09-06 20:46:42,674 basehttp 7196 9756 "GET /hw3/orders HTTP/1.1" 301 0
INFO 2023-09-06 20:46:42,909 basehttp 7196 2800 "GET /hw3/orders/ HTTP/1.1" 200 38833
INFO 2023-09-06 20:46:56,652 basehttp 7196 2800 "GET /hw3/products/ HTTP/1.1" 200 1884
INFO 2023-09-07 08:41:35,132 autoreload 4148 10076 Watching for file changes with StatReloader
INFO 2023-09-07 08:43:50,532 autoreload 1204 10300 Watching for file changes with StatReloader
INFO 2023-09-07 08:54:12,184 autoreload 12180 9420 Watching for file changes with StatReloader
INFO 2023-09-07 08:54:24,784 autoreload 12180 9420 C:\PY\django\myproject\s3app\urls.py changed, reloading.
INFO 2023-09-07 08:54:25,667 autoreload 260 11564 Watching for file changes with StatReloader
INFO 2023-09-07 08:54:30,145 autoreload 12312 12456 Watching for file changes with StatReloader
INFO 2023-09-07 08:54:46,731 autoreload 12312 12456 C:\PY\django\myproject\s3app\views.py changed, reloading.
INFO 2023-09-07 08:54:50,507 autoreload 3580 2484 Watching for file changes with StatReloader
INFO 2023-09-07 08:56:21,731 autoreload 3580 2484 C:\PY\django\myproject\my_project\settings.py changed, reloading.
INFO 2023-09-07 08:56:22,718 autoreload 10676 9920 Watching for file changes with StatReloader
INFO 2023-09-07 08:56:30,487 autoreload 8040 8272 Watching for file changes with StatReloader
INFO 2023-09-07 08:56:34,665 basehttp 8040 12996 "GET / HTTP/1.1" 200 13
WARNING 2023-09-07 08:56:35,373 log 8040 12996 Not Found: /favicon.ico
WARNING 2023-09-07 08:56:35,373 basehttp 8040 12996 "GET /favicon.ico HTTP/1.1" 404 3272
INFO 2023-09-07 08:56:50,256 basehttp 8040 12996 "GET /s3 HTTP/1.1" 301 0
ERROR 2023-09-07 08:56:50,645 log 8040 6188 Internal Server Error: /s3/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\s3app\views.py", line 16, in index
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_app/index.html
ERROR 2023-09-07 08:56:50,650 basehttp 8040 6188 "GET /s3/ HTTP/1.1" 500 81215
ERROR 2023-09-07 08:57:54,015 log 8040 6188 Internal Server Error: /s3/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\s3app\views.py", line 16, in index
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_app/index.html
ERROR 2023-09-07 08:57:54,018 basehttp 8040 6188 "GET /s3/ HTTP/1.1" 500 81352
INFO 2023-09-07 08:57:54,152 autoreload 8040 8272 C:\PY\django\myproject\s3app\urls.py changed, reloading.
INFO 2023-09-07 08:57:55,019 autoreload 7340 6828 Watching for file changes with StatReloader
ERROR 2023-09-07 08:59:25,445 log 7340 10964 Internal Server Error: /s3/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\s3app\views.py", line 16, in index
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_app/index.html
ERROR 2023-09-07 08:59:25,450 basehttp 7340 10964 "GET /s3/ HTTP/1.1" 500 81346
INFO 2023-09-07 08:59:26,348 autoreload 7340 6828 C:\PY\django\myproject\s3app\views.py changed, reloading.
INFO 2023-09-07 08:59:27,227 autoreload 12464 2724 Watching for file changes with StatReloader
INFO 2023-09-07 08:59:33,590 basehttp 12464 8248 "GET /s3/ HTTP/1.1" 200 405
INFO 2023-09-07 08:59:40,109 basehttp 12464 8248 "GET /s3/about HTTP/1.1" 301 0
ERROR 2023-09-07 08:59:40,259 log 12464 12012 Internal Server Error: /s3/about/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: s3/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\s3app\views.py", line 27, in about
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\PY\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: s3/base.html
ERROR 2023-09-07 08:59:40,268 basehttp 12464 12012 "GET /s3/about/ HTTP/1.1" 500 130994
INFO 2023-09-07 09:00:32,333 autoreload 6772 12064 Watching for file changes with StatReloader
INFO 2023-09-07 09:00:35,099 basehttp 6772 10068 "GET /s3/about/ HTTP/1.1" 200 400
INFO 2023-09-07 09:01:02,082 basehttp 6772 10068 "GET /s3/heads_game/5 HTTP/1.1" 200 537
INFO 2023-09-07 09:01:18,021 basehttp 6772 10068 "GET /s3/dice_game/6 HTTP/1.1" 200 515
INFO 2023-09-07 09:01:35,826 autoreload 6772 12064 C:\PY\django\myproject\s3app\views.py changed, reloading.
INFO 2023-09-07 09:01:36,698 autoreload 2008 11800 Watching for file changes with StatReloader
INFO 2023-09-07 09:01:40,449 basehttp 2008 9776 "GET /s3/dice_game/6 HTTP/1.1" 200 515
INFO 2023-09-07 09:01:42,797 basehttp 2008 9776 "GET /s3/dice_game/6 HTTP/1.1" 200 515
INFO 2023-09-07 09:01:43,400 basehttp 2008 9776 "GET /s3/dice_game/6 HTTP/1.1" 200 515
INFO 2023-09-07 09:01:43,908 basehttp 2008 9776 "GET /s3/dice_game/6 HTTP/1.1" 200 515
INFO 2023-09-07 09:03:03,295 autoreload 13164 12304 Watching for file changes with StatReloader
WARNING 2023-09-07 09:03:09,338 log 13164 5832 Not Found: /s4
WARNING 2023-09-07 09:03:09,339 basehttp 13164 5832 "GET /s4 HTTP/1.1" 404 3245
WARNING 2023-09-07 09:03:24,617 log 13164 12672 Not Found: /hw4
WARNING 2023-09-07 09:03:24,619 basehttp 13164 12672 "GET /hw4 HTTP/1.1" 404 3248
INFO 2023-09-07 09:03:40,065 basehttp 13164 392 "GET /hw3 HTTP/1.1" 301 0
ERROR 2023-09-07 09:03:40,145 log 13164 1032 Internal Server Error: /hw3/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: seminar_app/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\hw_3_app\views.py", line 26, in index
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\PY\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: seminar_app/base.html
ERROR 2023-09-07 09:03:40,154 basehttp 13164 1032 "GET /hw3/ HTTP/1.1" 500 141706
INFO 2023-09-07 09:04:26,691 basehttp 13164 4148 "GET /hw3/ HTTP/1.1" 200 1110
INFO 2023-09-07 09:06:31,467 basehttp 13164 4148 "GET /hw3/ HTTP/1.1" 200 1110
INFO 2023-09-07 09:06:31,517 autoreload 13164 12304 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:06:32,483 autoreload 10228 10768 Watching for file changes with StatReloader
INFO 2023-09-07 09:06:34,156 basehttp 10228 7844 "GET /hw3/ HTTP/1.1" 200 1098
INFO 2023-09-07 09:07:12,424 basehttp 10228 11792 "GET /hw3/ HTTP/1.1" 200 1098
INFO 2023-09-07 09:07:13,100 autoreload 10228 10768 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:07:13,982 autoreload 12732 11360 Watching for file changes with StatReloader
INFO 2023-09-07 09:07:16,144 basehttp 12732 11544 "GET /hw3/ HTTP/1.1" 200 1226
INFO 2023-09-07 09:08:09,782 basehttp 12732 9468 "GET /hw3/ HTTP/1.1" 200 1226
INFO 2023-09-07 09:08:10,623 autoreload 12732 11360 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:08:11,506 autoreload 12180 2816 Watching for file changes with StatReloader
INFO 2023-09-07 09:08:12,002 basehttp 12180 1032 "GET /hw3/ HTTP/1.1" 200 1162
INFO 2023-09-07 09:10:32,674 basehttp 12180 1032 "GET /hw3/ HTTP/1.1" 200 1162
INFO 2023-09-07 09:10:33,446 autoreload 12180 2816 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:10:34,400 autoreload 3888 13164 Watching for file changes with StatReloader
INFO 2023-09-07 09:10:40,750 basehttp 3888 10708 "GET /hw3/ HTTP/1.1" 200 1021
INFO 2023-09-07 09:11:07,133 basehttp 3888 10708 "GET /hw3/about HTTP/1.1" 301 0
INFO 2023-09-07 09:11:07,171 basehttp 3888 10000 "GET /hw3/about/ HTTP/1.1" 200 374
INFO 2023-09-07 09:11:24,803 basehttp 3888 10000 "GET /hw3/clients/ HTTP/1.1" 200 421
INFO 2023-09-07 09:11:45,129 basehttp 3888 10000 "GET /hw3/products/ HTTP/1.1" 200 1884
INFO 2023-09-07 09:12:01,952 basehttp 3888 10000 "GET /hw3/orders/ HTTP/1.1" 200 38833
INFO 2023-09-07 09:13:30,635 autoreload 3888 13164 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:13:31,705 autoreload 13104 8340 Watching for file changes with StatReloader
INFO 2023-09-07 09:14:56,011 autoreload 13104 8340 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:14:56,975 autoreload 12812 7548 Watching for file changes with StatReloader
INFO 2023-09-07 09:18:12,307 autoreload 12812 7548 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:18:13,183 autoreload 10036 10672 Watching for file changes with StatReloader
INFO 2023-09-07 09:18:29,320 autoreload 10036 10672 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:18:30,242 autoreload 3880 11380 Watching for file changes with StatReloader
INFO 2023-09-07 09:24:45,477 autoreload 3880 11380 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:24:46,559 autoreload 10016 11780 Watching for file changes with StatReloader
INFO 2023-09-07 09:26:01,312 autoreload 10016 11780 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:26:02,214 autoreload 11420 8048 Watching for file changes with StatReloader
INFO 2023-09-07 09:26:48,026 autoreload 11420 8048 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:26:49,269 autoreload 8 8456 Watching for file changes with StatReloader
INFO 2023-09-07 09:36:04,434 autoreload 8 8456 C:\PY\django\myproject\hw_3_app\views.py changed, reloading.
INFO 2023-09-07 09:36:05,349 autoreload 10052 7116 Watching for file changes with StatReloader
ERROR 2023-09-07 09:36:19,510 log 10052 4780 Internal Server Error: /hw3/product_orders/
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\hw_3_app\views.py", line 64, in get_context_data
    client = Client.objects.get(pk=self.kwargs['pk'])
                                   ~~~~~~~~~~~^^^^^^
KeyError: 'pk'
ERROR 2023-09-07 09:36:19,515 basehttp 10052 4780 "GET /hw3/product_orders/ HTTP/1.1" 500 83358
WARNING 2023-09-07 09:42:10,296 log 10052 10944 Not Found: /hw3/product_orders/2
WARNING 2023-09-07 09:42:10,297 basehttp 10052 10944 "GET /hw3/product_orders/2 HTTP/1.1" 404 4246
INFO 2023-09-07 09:43:30,060 autoreload 10052 7116 C:\PY\django\myproject\hw_3_app\urls.py changed, reloading.
INFO 2023-09-07 09:43:31,327 autoreload 11520 13148 Watching for file changes with StatReloader
INFO 2023-09-07 09:43:34,794 basehttp 11520 11708 "GET /hw3/product_orders/2 HTTP/1.1" 200 471
INFO 2023-09-07 09:43:44,466 basehttp 11520 8388 "GET /hw3/product_orders/3 HTTP/1.1" 200 471
INFO 2023-09-07 09:43:50,297 basehttp 11520 10672 "GET /hw3/product_orders/5 HTTP/1.1" 200 471
INFO 2023-09-07 09:56:03,187 basehttp 11520 10096 "GET /hw3/product_orders/3 HTTP/1.1" 200 471
INFO 2023-09-07 09:57:16,054 basehttp 11520 9140 "GET /hw3/product_orders/6 HTTP/1.1" 200 471
INFO 2023-09-07 09:57:21,597 basehttp 11520 8616 "GET /hw3/product_orders/10 HTTP/1.1" 200 473
ERROR 2023-09-07 09:57:29,190 log 11520 3732 Internal Server Error: /hw3/product_orders/20
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\myproject\hw_3_app\views.py", line 64, in get_context_data
    client = Client.objects.get(pk=self.kwargs['pk'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
hw_3_app.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2023-09-07 09:57:29,196 basehttp 11520 3732 "GET /hw3/product_orders/20 HTTP/1.1" 500 92715
INFO 2023-09-07 09:58:17,795 basehttp 11520 1476 "GET /hw3/product_orders/5 HTTP/1.1" 200 471
INFO 2023-09-07 09:59:21,158 basehttp 11520 10548 "GET /hw3/product_orders/5 HTTP/1.1" 200 471
INFO 2023-09-07 09:59:22,949 basehttp 11520 10548 "GET /hw3/product_orders/5 HTTP/1.1" 200 471
INFO 2023-09-07 10:01:10,440 basehttp 11520 11516 "GET /hw3/product_orders/5 HTTP/1.1" 200 471
INFO 2023-09-07 10:01:12,405 basehttp 11520 11516 "GET /hw3/product_orders/5 HTTP/1.1" 200 471
ERROR 2023-09-07 10:03:55,067 log 11520 12012 Internal Server Error: /hw3/product_orders/5
Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\PY\django\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2023-09-07 10:03:55,079 basehttp 11520 12012 "GET /hw3/product_orders/5 HTTP/1.1" 500 181324
INFO 2023-09-08 17:07:28,849 autoreload 8328 140395072864256 Watching for file changes with StatReloader
INFO 2023-09-08 17:07:58,542 basehttp 8328 140395020285504 "GET /hw3/products HTTP/1.1" 301 0
INFO 2023-09-08 17:07:58,550 basehttp 8328 140395010844224 "GET /hw3/products/ HTTP/1.1" 200 1884
INFO 2023-09-08 17:08:58,885 autoreload 8328 140395072864256 /home/alevtin/GB/Flask/django/myproject/hw_3_app/models.py changed, reloading.
INFO 2023-09-08 17:08:59,470 autoreload 8381 140577258311680 Watching for file changes with StatReloader
INFO 2023-09-08 17:51:20,044 autoreload 9260 139827875176448 Watching for file changes with StatReloader
INFO 2023-09-08 17:51:45,472 autoreload 9260 139827875176448 /home/alevtin/GB/Flask/django/myproject/my_project/settings.py changed, reloading.
INFO 2023-09-08 17:51:46,218 autoreload 9278 139914608586752 Watching for file changes with StatReloader
INFO 2023-09-08 17:51:50,024 basehttp 9278 139914555422272 "GET / HTTP/1.1" 200 13
INFO 2023-09-08 17:52:02,884 basehttp 9278 139914555422272 "GET /hw3 HTTP/1.1" 301 0
INFO 2023-09-08 17:52:02,897 basehttp 9278 139914547029568 "GET /hw3/ HTTP/1.1" 200 1021
INFO 2023-09-08 17:52:33,917 basehttp 9278 139914547029568 "GET /hw3/product_orders/10 HTTP/1.1" 200 369
INFO 2023-09-08 17:52:40,223 basehttp 9278 139914547029568 "GET /hw3/product_orders/5 HTTP/1.1" 200 369
INFO 2023-09-08 17:53:38,003 basehttp 9278 139914547029568 "GET /hw3/product_orders/5 HTTP/1.1" 200 369
WARNING 2023-09-08 17:53:48,020 log 9278 139914547029568 Not Found: /hw3/product_orders/
WARNING 2023-09-08 17:53:48,020 basehttp 9278 139914547029568 "GET /hw3/product_orders/ HTTP/1.1" 404 4257
INFO 2023-09-08 17:53:53,628 basehttp 9278 139914547029568 "GET /hw3/product_orders/5 HTTP/1.1" 200 369
INFO 2023-09-09 06:11:39,299 autoreload 4662 139851009572864 Watching for file changes with StatReloader
INFO 2023-09-09 07:34:26,498 autoreload 5752 140514313822208 Watching for file changes with StatReloader
INFO 2023-09-09 07:34:29,389 basehttp 5752 140514261202496 "GET / HTTP/1.1" 200 13
WARNING 2023-09-09 07:34:29,698 log 5752 140514261202496 Not Found: /favicon.ico
WARNING 2023-09-09 07:34:29,701 basehttp 5752 140514261202496 "GET /favicon.ico HTTP/1.1" 404 3375
INFO 2023-09-09 07:34:57,852 basehttp 5752 140514261202496 "GET /s4 HTTP/1.1" 301 0
INFO 2023-09-09 07:34:57,888 basehttp 5752 140514251761216 "GET /s4/ HTTP/1.1" 200 502
INFO 2023-09-09 07:34:57,926 basehttp 5752 140514251761216 "GET /static/css/bootstrap.css HTTP/1.1" 200 287892
INFO 2023-09-09 07:35:27,230 basehttp 5752 140514251761216 "GET /s4/about/ HTTP/1.1" 200 497
INFO 2023-09-09 07:35:42,461 basehttp 5752 140514251761216 "GET /s4/heads_game/5 HTTP/1.1" 200 634
INFO 2023-09-09 07:36:07,775 basehttp 5752 140514251761216 "GET /s4/dice_game/5 HTTP/1.1" 200 590
INFO 2023-09-09 07:36:07,804 basehttp 5752 140514251761216 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
ERROR 2023-09-09 07:36:24,003 log 5752 140514251761216 Internal Server Error: /s4/articles/5
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
  File "/home/alevtin/GB/Flask/django/myproject/seminar_app/views.py", line 61, in get_context_data
    author = Author.objects.get(pk=self.kwargs['pk'])
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
seminar_app.models.Author.DoesNotExist: Author matching query does not exist.
ERROR 2023-09-09 07:36:24,010 basehttp 5752 140514251761216 "GET /s4/articles/5 HTTP/1.1" 500 90899
WARNING 2023-09-09 07:36:48,243 log 5752 140514251761216 Not Found: /s4/article/5
WARNING 2023-09-09 07:36:48,245 basehttp 5752 140514251761216 "GET /s4/article/5 HTTP/1.1" 404 4549
WARNING 2023-09-09 07:37:39,803 log 5752 140514251761216 Not Found: /s4/article/
WARNING 2023-09-09 07:37:39,804 basehttp 5752 140514251761216 "GET /s4/article/ HTTP/1.1" 404 5621
INFO 2023-09-09 07:37:50,222 basehttp 5752 140514251761216 "GET /s4/author/ HTTP/1.1" 200 0
INFO 2023-09-09 07:38:11,469 basehttp 5752 140514251761216 "GET /s4/add_author/ HTTP/1.1" 200 1387
INFO 2023-09-09 07:38:11,498 basehttp 5752 140514251761216 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
INFO 2023-09-09 07:38:40,916 basehttp 5752 140514251761216 "GET /s4/article/add HTTP/1.1" 200 1340
INFO 2023-09-09 07:48:52,926 autoreload 6393 139980866613248 Watching for file changes with StatReloader
INFO 2023-09-09 07:49:14,683 basehttp 6393 139980813891136 "GET /s4/author/ HTTP/1.1" 200 0
INFO 2023-09-09 07:49:18,586 basehttp 6393 139980813891136 "GET /s4/author/ HTTP/1.1" 200 0
INFO 2023-09-09 07:49:19,571 basehttp 6393 139980813891136 "GET /s4/author/ HTTP/1.1" 200 0
INFO 2023-09-09 07:49:39,190 basehttp 6393 139980813891136 "GET /s4/add_author/ HTTP/1.1" 200 1387
INFO 2023-09-09 07:49:39,208 basehttp 6393 139980813891136 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
ERROR 2023-09-09 07:51:26,504 log 6393 139980813891136 Internal Server Error: /s4/add_author/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/forms/models.py", line 542, in save
    self.instance.save()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/base/operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/utils.py", line 97, in inner
    with self:
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2023-09-09 07:51:26,510 basehttp 6393 139980813891136 "POST /s4/add_author/ HTTP/1.1" 500 152461
INFO 2023-09-09 07:51:48,909 basehttp 6393 139980813891136 "POST /s4/add_author/ HTTP/1.1" 302 0
INFO 2023-09-09 07:51:48,920 basehttp 6393 139980813891136 "GET /s4/author_page/1 HTTP/1.1" 200 443
INFO 2023-09-09 07:52:06,708 basehttp 6393 139980813891136 "GET /s4/author_page/1 HTTP/1.1" 200 443
INFO 2023-09-09 07:52:37,257 basehttp 6393 139980813891136 "GET /s4/add_author/ HTTP/1.1" 200 1387
INFO 2023-09-09 07:52:37,296 basehttp 6393 139980813891136 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
INFO 2023-09-09 07:53:13,673 basehttp 6393 139980813891136 "POST /s4/add_author/ HTTP/1.1" 302 0
INFO 2023-09-09 07:53:13,680 basehttp 6393 139980813891136 "GET /s4/author_page/2 HTTP/1.1" 200 443
INFO 2023-09-09 07:53:36,033 basehttp 6393 139980813891136 "POST /s4/add_author/ HTTP/1.1" 302 0
INFO 2023-09-09 07:53:36,042 basehttp 6393 139980813891136 "GET /s4/author_page/3 HTTP/1.1" 200 443
INFO 2023-09-09 07:53:44,382 basehttp 6393 139980813891136 "GET /s4/author HTTP/1.1" 301 0
INFO 2023-09-09 07:53:44,400 basehttp 6393 139980813891136 "GET /s4/author/ HTTP/1.1" 200 75
INFO 2023-09-09 07:54:11,044 basehttp 6393 139980813891136 "GET /s4/article/add HTTP/1.1" 200 1496
INFO 2023-09-09 07:57:12,840 basehttp 6393 139980813891136 "GET /s4/article/add HTTP/1.1" 200 1496
INFO 2023-09-09 07:57:12,898 basehttp 6393 139980813891136 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
INFO 2023-09-09 08:04:22,209 autoreload 7083 139844203606016 Watching for file changes with StatReloader
WARNING 2023-09-09 08:04:33,283 log 7083 139844150883904 Not Found: /s4/categorye/add
WARNING 2023-09-09 08:04:33,286 basehttp 7083 139844150883904 "GET /s4/categorye/add HTTP/1.1" 404 5819
ERROR 2023-09-09 08:04:41,756 log 7083 139844150883904 Internal Server Error: /s4/category/add
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_app/add_category.html
ERROR 2023-09-09 08:04:41,760 basehttp 7083 139844150883904 "GET /s4/category/add HTTP/1.1" 500 85211
INFO 2023-09-09 08:05:32,076 basehttp 7083 139844150883904 "GET /s4/category/add HTTP/1.1" 200 795
INFO 2023-09-09 08:05:32,100 basehttp 7083 139844150883904 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
ERROR 2023-09-09 08:05:45,672 log 7083 139844150883904 Internal Server Error: /s4/category/add
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
AttributeError: 'Category' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 127, in get_success_url
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.
ERROR 2023-09-09 08:05:45,678 basehttp 7083 139844150883904 "POST /s4/category/add HTTP/1.1" 500 100701
ERROR 2023-09-09 08:06:50,544 log 7083 139844150883904 Internal Server Error: /s4/category/add
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
AttributeError: 'Category' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 127, in get_success_url
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.
ERROR 2023-09-09 08:06:50,550 basehttp 7083 139844150883904 "POST /s4/category/add HTTP/1.1" 500 100701
ERROR 2023-09-09 08:06:58,151 log 7083 139844150883904 Internal Server Error: /s4/category/add
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
AttributeError: 'Category' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 127, in get_success_url
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.
ERROR 2023-09-09 08:06:58,153 basehttp 7083 139844150883904 "POST /s4/category/add HTTP/1.1" 500 100701
INFO 2023-09-09 08:10:32,255 basehttp 7083 139844150883904 "GET /s4/article/add HTTP/1.1" 200 1646
INFO 2023-09-09 08:10:32,312 basehttp 7083 139844150883904 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
INFO 2023-09-09 08:10:58,088 basehttp 7083 139844150883904 "POST /s4/article/add HTTP/1.1" 302 0
ERROR 2023-09-09 08:10:58,549 log 7083 139844150883904 Internal Server Error: /s4/article/1
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_app/article_page.html
ERROR 2023-09-09 08:10:58,552 basehttp 7083 139844150883904 "GET /s4/article/1 HTTP/1.1" 500 85503
ERROR 2023-09-09 08:11:32,902 log 7083 139844150883904 Internal Server Error: /s4/article/1
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_app/article_page.html
ERROR 2023-09-09 08:11:32,912 basehttp 7083 139844150883904 "GET /s4/article/1 HTTP/1.1" 500 85503
INFO 2023-09-09 08:13:41,129 autoreload 7083 139844203606016 /home/alevtin/GB/Flask/django/myproject/seminar_app/views.py changed, reloading.
INFO 2023-09-09 08:13:41,721 autoreload 7864 140486345711616 Watching for file changes with StatReloader
INFO 2023-09-09 08:37:34,608 autoreload 8576 140240350871552 Watching for file changes with StatReloader
INFO 2023-09-09 08:37:38,720 basehttp 8576 140240296605248 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 08:37:47,977 basehttp 8576 140240296605248 "GET /hw4 HTTP/1.1" 301 0
INFO 2023-09-09 08:37:47,984 basehttp 8576 140240288212544 "GET /hw4/ HTTP/1.1" 200 41
INFO 2023-09-09 08:38:20,393 basehttp 8576 140240288212544 "GET /hw4/about/ HTTP/1.1" 200 40
WARNING 2023-09-09 08:38:33,892 log 8576 140240288212544 Not Found: /hw4/about/customer/1
WARNING 2023-09-09 08:38:33,892 basehttp 8576 140240288212544 "GET /hw4/about/customer/1 HTTP/1.1" 404 5024
WARNING 2023-09-09 08:39:20,545 log 8576 140240288212544 Not Found: /hw4/about/customer/
WARNING 2023-09-09 08:39:20,548 basehttp 8576 140240288212544 "GET /hw4/about/customer/ HTTP/1.1" 404 5021
INFO 2023-09-09 08:39:46,408 basehttp 8576 140240288212544 "GET /hw4/customer/1 HTTP/1.1" 301 0
ERROR 2023-09-09 08:39:46,534 log 8576 140240296605248 Internal Server Error: /hw4/customer/1/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: hw_4_app_customer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: hw_4_app_customer
ERROR 2023-09-09 08:39:46,542 basehttp 8576 140240296605248 "GET /hw4/customer/1/ HTTP/1.1" 500 150137
INFO 2023-09-09 08:49:56,637 autoreload 9256 140127349612544 Watching for file changes with StatReloader
INFO 2023-09-09 08:50:21,205 basehttp 9256 140127295764032 "GET /hw4/ HTTP/1.1" 200 41
INFO 2023-09-09 08:50:41,653 basehttp 9256 140127295764032 "GET /hw4/customer/2 HTTP/1.1" 301 0
ERROR 2023-09-09 08:50:41,737 log 9256 140127287371328 Internal Server Error: /hw4/customer/2/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_app/customer_page.html
ERROR 2023-09-09 08:50:41,743 basehttp 9256 140127287371328 "GET /hw4/customer/2/ HTTP/1.1" 500 85563
WARNING 2023-09-09 08:51:07,463 log 9256 140127287371328 Not Found: /hw4/product/
WARNING 2023-09-09 08:51:07,464 basehttp 9256 140127287371328 "GET /hw4/product/ HTTP/1.1" 404 5000
INFO 2023-09-09 08:51:12,995 basehttp 9256 140127287371328 "GET /hw4/product/1 HTTP/1.1" 301 0
ERROR 2023-09-09 08:51:13,068 log 9256 140127295764032 Internal Server Error: /hw4/product/1/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_app/product_page.html
ERROR 2023-09-09 08:51:13,072 basehttp 9256 140127295764032 "GET /hw4/product/1/ HTTP/1.1" 500 85527
ERROR 2023-09-09 08:54:41,094 log 9256 140127295764032 Internal Server Error: /hw4/product/1/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_app/product_page.html
ERROR 2023-09-09 08:54:41,097 basehttp 9256 140127295764032 "GET /hw4/product/1/ HTTP/1.1" 500 85664
INFO 2023-09-09 08:56:13,723 basehttp 9256 140127295764032 "GET /hw4/ HTTP/1.1" 200 41
INFO 2023-09-09 08:56:19,499 basehttp 9256 140127295764032 "GET /hw4/about HTTP/1.1" 301 0
INFO 2023-09-09 08:56:19,508 basehttp 9256 140127287371328 "GET /hw4/about/ HTTP/1.1" 200 40
INFO 2023-09-09 08:59:22,952 basehttp 9256 140127287371328 "GET /hw4/update_product/2 HTTP/1.1" 301 0
ERROR 2023-09-09 08:59:23,019 log 9256 140127295764032 Internal Server Error: /hw4/update_product/2/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_app/update_product.html
ERROR 2023-09-09 08:59:23,026 basehttp 9256 140127295764032 "GET /hw4/update_product/2/ HTTP/1.1" 500 85648
ERROR 2023-09-09 09:01:27,500 log 9256 140127295764032 Internal Server Error: /hw4/update_product/2/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_app/update_product.html
ERROR 2023-09-09 09:01:27,501 basehttp 9256 140127295764032 "GET /hw4/update_product/2/ HTTP/1.1" 500 85785
INFO 2023-09-09 09:01:28,224 autoreload 9256 140127349612544 /home/alevtin/GB/Flask/django/myproject/hw_4_app/views.py changed, reloading.
INFO 2023-09-09 09:01:28,860 autoreload 9395 140592455360512 Watching for file changes with StatReloader
INFO 2023-09-09 09:01:39,446 autoreload 9395 140592455360512 /home/alevtin/GB/Flask/django/myproject/hw_4_app/views.py changed, reloading.
INFO 2023-09-09 09:01:40,167 autoreload 9400 139747282415616 Watching for file changes with StatReloader
ERROR 2023-09-09 09:01:42,539 log 9400 139747158652480 Internal Server Error: /hw4/update_product/2/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4_app' is not a registered namespace
ERROR 2023-09-09 09:01:42,544 basehttp 9400 139747158652480 "GET /hw4/update_product/2/ HTTP/1.1" 500 164366
INFO 2023-09-09 09:04:41,407 autoreload 9400 139747282415616 /home/alevtin/GB/Flask/django/myproject/hw_4_app/urls.py changed, reloading.
INFO 2023-09-09 09:04:42,222 autoreload 9503 140506044284928 Watching for file changes with StatReloader
INFO 2023-09-09 09:04:42,593 basehttp 9503 140505991083584 "GET /hw4/update_product/2/ HTTP/1.1" 200 1905
INFO 2023-09-09 09:04:42,617 basehttp 9503 140505991083584 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
INFO 2023-09-09 09:09:40,796 basehttp 9503 140505991083584 "GET /hw4/customer/1/ HTTP/1.1" 200 702
WARNING 2023-09-09 09:09:45,077 log 9503 140505991083584 Not Found: /hw4/orders/year/2023/1/
WARNING 2023-09-09 09:09:45,078 basehttp 9503 140505991083584 "GET /hw4/orders/year/2023/1/ HTTP/1.1" 404 4301
WARNING 2023-09-09 09:10:10,804 log 9503 140505991083584 Not Found: /hw4/orders/week/2023/36/1/
WARNING 2023-09-09 09:10:10,806 basehttp 9503 140505991083584 "GET /hw4/orders/week/2023/36/1/ HTTP/1.1" 404 4783
INFO 2023-09-09 09:10:40,909 basehttp 9503 140505991083584 "GET /hw4/customer/5 HTTP/1.1" 301 0
INFO 2023-09-09 09:10:40,920 basehttp 9503 140505982690880 "GET /hw4/customer/5/ HTTP/1.1" 200 702
ERROR 2023-09-09 09:10:45,325 log 9503 140505982690880 Internal Server Error: /hw4/orders/week/2023/36/5/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_4_app/all_products.html, hw_4_app/order_archive.html
ERROR 2023-09-09 09:10:45,333 basehttp 9503 140505982690880 "GET /hw4/orders/week/2023/36/5/ HTTP/1.1" 500 89992
ERROR 2023-09-09 09:11:27,506 log 9503 140505982690880 Internal Server Error: /hw4/orders/week/2023/36/5/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_4_app/all_products.html, hw_4_app/order_archive.html
ERROR 2023-09-09 09:11:27,509 basehttp 9503 140505982690880 "GET /hw4/orders/week/2023/36/5/ HTTP/1.1" 500 89992
INFO 2023-09-09 09:11:55,976 basehttp 9503 140505982690880 "GET /hw4/product/2 HTTP/1.1" 301 0
INFO 2023-09-09 09:11:55,994 basehttp 9503 140505982690880 "GET /hw4/product/2/ HTTP/1.1" 200 608
WARNING 2023-09-09 09:11:56,054 log 9503 140505982690880 Not Found: /media/default.png
WARNING 2023-09-09 09:11:56,056 basehttp 9503 140505982690880 "GET /media/default.png HTTP/1.1" 404 3497
INFO 2023-09-09 09:11:58,103 basehttp 9503 140505982690880 "GET /hw4/update_product/2/ HTTP/1.1" 200 1905
ERROR 2023-09-09 09:12:12,333 log 9503 140505982690880 Internal Server Error: /hw4/update_product/2/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "/home/alevtin/GB/Flask/django/myproject/hw_4_app/models.py", line 32, in get_absolute_url
    return reverse('hw_app:product_page', kwargs={'pk': self.pk})
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_app' is not a registered namespace
ERROR 2023-09-09 09:12:12,335 basehttp 9503 140505982690880 "POST /hw4/update_product/2/ HTTP/1.1" 500 113534
INFO 2023-09-09 09:12:54,625 autoreload 9503 140506044284928 /home/alevtin/GB/Flask/django/myproject/hw_4_app/models.py changed, reloading.
INFO 2023-09-09 09:12:55,561 autoreload 9857 140695833055232 Watching for file changes with StatReloader
INFO 2023-09-09 09:12:56,164 basehttp 9857 140695780193856 "POST /hw4/update_product/2/ HTTP/1.1" 302 0
INFO 2023-09-09 09:12:56,193 basehttp 9857 140695780193856 "GET /hw4/product/2/ HTTP/1.1" 200 628
WARNING 2023-09-09 09:12:56,275 log 9857 140695780193856 Not Found: /media/product_image/books_ODEUeiM.jpg
WARNING 2023-09-09 09:12:56,276 basehttp 9857 140695780193856 "GET /media/product_image/books_ODEUeiM.jpg HTTP/1.1" 404 3557
INFO 2023-09-09 09:13:01,910 basehttp 9857 140695780193856 "GET /hw4/update_product/2/ HTTP/1.1" 200 1905
INFO 2023-09-09 09:13:12,925 basehttp 9857 140695780193856 "POST /hw4/update_product/2/ HTTP/1.1" 302 0
INFO 2023-09-09 09:13:12,933 basehttp 9857 140695780193856 "GET /hw4/product/2/ HTTP/1.1" 200 628
WARNING 2023-09-09 09:13:13,024 log 9857 140695780193856 Not Found: /media/product_image/books_GG3ELJ1.jpg
WARNING 2023-09-09 09:13:13,025 basehttp 9857 140695780193856 "GET /media/product_image/books_GG3ELJ1.jpg HTTP/1.1" 404 3557
WARNING 2023-09-09 09:13:24,934 log 9857 140695780193856 Not Found: /media/product_image/books_GG3ELJ1.jpg
WARNING 2023-09-09 09:13:24,935 basehttp 9857 140695780193856 "GET /media/product_image/books_GG3ELJ1.jpg HTTP/1.1" 404 3557
WARNING 2023-09-09 09:14:19,066 log 9857 140695780193856 Not Found: /media/product_image/books.jpg
WARNING 2023-09-09 09:14:19,068 basehttp 9857 140695780193856 "GET /media/product_image/books.jpg HTTP/1.1" 404 3533
INFO 2023-09-09 09:16:47,156 basehttp 9857 140695780193856 "GET /hw4/customer/2/ HTTP/1.1" 200 702
INFO 2023-09-09 09:16:47,192 basehttp 9857 140695780193856 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
WARNING 2023-09-09 09:16:51,486 log 9857 140695780193856 Not Found: /hw4/orders/week/2023/36/2/
WARNING 2023-09-09 09:16:51,487 basehttp 9857 140695780193856 "GET /hw4/orders/week/2023/36/2/ HTTP/1.1" 404 4783
WARNING 2023-09-09 09:18:16,227 log 9857 140695780193856 Not Found: /hw4/update_product/
WARNING 2023-09-09 09:18:16,231 basehttp 9857 140695780193856 "GET /hw4/update_product/ HTTP/1.1" 404 5021
INFO 2023-09-09 09:18:21,485 basehttp 9857 140695780193856 "GET /hw4/update_product/3 HTTP/1.1" 301 0
INFO 2023-09-09 09:18:21,512 basehttp 9857 140695771801152 "GET /hw4/update_product/3/ HTTP/1.1" 200 1905
INFO 2023-09-09 09:19:14,148 basehttp 9857 140695771801152 "POST /hw4/update_product/3/ HTTP/1.1" 302 0
INFO 2023-09-09 09:19:14,157 basehttp 9857 140695771801152 "GET /hw4/product/3/ HTTP/1.1" 200 622
WARNING 2023-09-09 09:19:14,238 log 9857 140695771801152 Not Found: /media/product_image/default.png
WARNING 2023-09-09 09:19:14,238 basehttp 9857 140695771801152 "GET /media/product_image/default.png HTTP/1.1" 404 3539
WARNING 2023-09-09 09:19:57,581 log 9857 140695771801152 Not Found: /media/product_image/default.png
WARNING 2023-09-09 09:19:57,583 basehttp 9857 140695771801152 "GET /media/product_image/default.png HTTP/1.1" 404 3539
INFO 2023-09-09 09:23:03,358 basehttp 9857 140695771801152 "GET /hw4/update_product/3/ HTTP/1.1" 200 1905
INFO 2023-09-09 09:23:11,179 basehttp 9857 140695771801152 "GET /hw4/product/3/ HTTP/1.1" 200 622
WARNING 2023-09-09 09:23:11,223 log 9857 140695771801152 Not Found: /media/product_image/default.png
WARNING 2023-09-09 09:23:11,227 basehttp 9857 140695771801152 "GET /media/product_image/default.png HTTP/1.1" 404 3539
INFO 2023-09-09 09:25:14,754 autoreload 9857 140695833055232 /home/alevtin/GB/Flask/django/myproject/hw_4_app/views.py changed, reloading.
INFO 2023-09-09 09:25:15,366 autoreload 10144 140182353682432 Watching for file changes with StatReloader
INFO 2023-09-09 09:25:18,659 basehttp 10144 140182229612096 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 09:25:36,596 basehttp 10144 140182229612096 "GET /hw4/ HTTP/1.1" 200 41
ERROR 2023-09-09 09:25:46,344 log 10144 140182229612096 Internal Server Error: /hw4/customer/5/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'yearly_orders' not found. 'yearly_orders' is not a valid view function or pattern name.
ERROR 2023-09-09 09:25:46,348 basehttp 10144 140182229612096 "GET /hw4/customer/5/ HTTP/1.1" 500 164925
ERROR 2023-09-09 09:27:17,839 log 10144 140182229612096 Internal Server Error: /hw4/customer/5/
Traceback (most recent call last):
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/alevtin/GB/Flask/django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'yearly_orders' not found. 'yearly_orders' is not a valid view function or pattern name.
ERROR 2023-09-09 09:27:17,841 basehttp 10144 140182229612096 "GET /hw4/customer/5/ HTTP/1.1" 500 165062
INFO 2023-09-09 09:27:32,713 basehttp 10144 140182229612096 "GET /hw4/customer/5/ HTTP/1.1" 200 502
WARNING 2023-09-09 09:27:45,196 log 10144 140182229612096 Not Found: /hw4/product+/5/
WARNING 2023-09-09 09:27:45,197 basehttp 10144 140182229612096 "GET /hw4/product+/5/ HTTP/1.1" 404 4319
INFO 2023-09-09 09:27:55,105 basehttp 10144 140182229612096 "GET /hw4/product/5/ HTTP/1.1" 200 608
WARNING 2023-09-09 09:27:55,155 log 10144 140182229612096 Not Found: /media/default.png
WARNING 2023-09-09 09:27:55,156 basehttp 10144 140182229612096 "GET /media/default.png HTTP/1.1" 404 3497
INFO 2023-09-09 09:28:00,959 basehttp 10144 140182229612096 "GET /hw4/update_product/5/ HTTP/1.1" 200 1905
INFO 2023-09-09 09:28:10,868 basehttp 10144 140182229612096 "POST /hw4/update_product/5/ HTTP/1.1" 302 0
INFO 2023-09-09 09:28:10,876 basehttp 10144 140182229612096 "GET /hw4/product/5/ HTTP/1.1" 200 608
INFO 2023-09-09 09:28:10,944 basehttp 10144 140182221219392 "GET /static/css/bootstrap.css HTTP/1.1" 304 0
WARNING 2023-09-09 09:28:10,949 log 10144 140182229612096 Not Found: /media/default.png
WARNING 2023-09-09 09:28:10,950 basehttp 10144 140182229612096 "GET /media/default.png HTTP/1.1" 404 3497
INFO 2023-09-09 09:28:14,214 basehttp 10144 140182229612096 "GET /hw4/update_product/5/ HTTP/1.1" 200 1905
INFO 2023-09-09 09:28:33,900 basehttp 10144 140182229612096 "POST /hw4/update_product/5/ HTTP/1.1" 302 0
INFO 2023-09-09 09:28:33,910 basehttp 10144 140182229612096 "GET /hw4/product/5/ HTTP/1.1" 200 628
WARNING 2023-09-09 09:28:33,999 log 10144 140182229612096 Not Found: /media/product_image/books_ACJx5zA.jpg
WARNING 2023-09-09 09:28:34,000 basehttp 10144 140182229612096 "GET /media/product_image/books_ACJx5zA.jpg HTTP/1.1" 404 3557
WARNING 2023-09-09 09:28:52,586 log 10144 140182229612096 Not Found: /media/product_image/books_ACJx5zA.jpg
WARNING 2023-09-09 09:28:52,588 basehttp 10144 140182229612096 "GET /media/product_image/books_ACJx5zA.jpg HTTP/1.1" 404 3557
